### ISSUE TITLE
Upload files and directories [object Object] %

### ISSUE THREAD

**Issue by Arthurlouge** [CodeboxIDE/codebox#215]
While uploading the percentages does not appear:

![screen shot 2014-01-29 at 13 48 23](https://f.cloud.github.com/assets/4077385/2029823/689e97b6-88ec-11e3-9ef2-3d59e779d9e6.png)

**Comment by nkamaras** [comment]
How can I upload a audio file to Codebox?

**Comment by nkamaras** [comment]
Excuse me,how can I upload an audio file to Codebox from Windows?
