### ISSUE TITLE
I open Terminal and see `aN;NaNf`, it's a problem?

### ISSUE THREAD

**Issue by wwb-dev** [CodeboxIDE/codebox#455]
![log](https://cloud.githubusercontent.com/assets/1448791/5233199/fe96609c-77ab-11e4-8aad-1e485ab112d0.png)

**Comment by kozhin** [comment]
I have the same issue with the latest version of codebox. And the terminal box is totally unusable. Entered symbols aren't visible at all. But I see entered symbols in the server terminal where I started codebox.
