### ISSUE TITLE
Failed at the ctags@0.11.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by ibewugb** [CodeboxIDE/codebox#483]
Hi, I'm getting the following error while doing "sudo npm install -g codebox"

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "codebox"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! ctags@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@0.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/foo/npm-debug.log

**Comment by listepo** [comment]
@ibewugb, ctags needs to be updated.

**Comment by listepo** [comment]
Hard to do the update dependencies without tests

**Comment by etopian** [comment]
It does not seem as if there are any significant changes to the module, just dependencies of the module. Simply bumping versions on the module works fine and there is a pull request on the module for just that.
