### ISSUE TITLE
is it dead?

### ISSUE THREAD

**Issue by alugarius** [CodeboxIDE/codebox#522]
Because it seems so

**Comment by cmmata** [comment]
@alugarius see #518 and #521

**Comment by nzinfo** [comment]
I've just made an effort that make codebox alpha5 running on the lastest node(7.4.x) . And there's still some bug in it. eg. hard to type Chinese in editor & terminal... ， But it just run.
https://github.com/coreseekdev/codebox

**Comment by ShadowRZ** [comment]
Maybe it's really dead.
Because certificate expired.

**Comment by alugarius** [comment]
Closing cause its ded
